#OBJS specifies which files to compile as part of the project
OBJS = app.cpp

#OBJ_NAME specifies the name of our exectuable
OBJ_NAME = aplication

#This is the target that compiles our executable
all : $(OBJS)
	g++ $(OBJS) -w -lallegro_image -lallegro -o $(OBJ_NAME)
	./$(OBJ_NAME)
